### PR TITLE
Configure docker setup of pgh3 extension with postgis and pgrouting

### PR DESCRIPTION
**Pull request by zacdezgeo**
Hi,

I've recently been using pgh3 for some work and automating the configuration with docker really simplified my workflow. I thought it could be something that would be helpful for the community. 

Is this something that would add value to the project? Is there additional documentation that should be added?

So far, I only added the base Dockerfile and an example compose file using the image.

Let me know what changes should be done.

Cheers!

### CODE REVIEW

**Comment by nmandery** [comment]
Hi, thank you for your PR - that is definitely valuable to the project.

Maybe you can remove the `.idea` directory from the changeset.

This project belongs to the DLR EOC organization which is a company account. I just noticed I have forgotten to add the contributors agreement to this repository. Our legal department requires us to ask external contributors to sign this and send it to the email address in the document (a photo of it would be sufficient) before we are allowed to accept your contribution. The document is [here](https://github.com/dlr-eoc/ukis-pysat/blob/master/DLR_Individual_Contributor_License_Agreement_UKIS.pdf).

Thank you for your contribution and sorry for the inconvenience ;)

**Comment by zacdezgeo** [comment]
Thanks for the swift reply. I've removed the `.idea` configuration. 

I'll review the legal document and get back to you shortly.

**Comment by zacdezgeo** [comment]
I've just sent the license agreement to the email :pen:

**Comment by nmandery** [comment]
Thank you very much

**Pull request merged**
